version: '3'

services:
  db:
    image: mongo:5.0
    container_name: smart_ranking_mongodb
    ports:
      - 27017:27017
    restart: always

  api:
    image: smart_ranking_api
    build: .
    tty: true
    container_name: smart_ranking_api
    volumes:
      - .:/smart-ranking-api
      - ./node_modules:/smart-ranking-api/node_modules
    ports:
      - 8080:8080
    command: bash -c "npm run start:dev"
